kind: ClusterConfiguration
apiVersion: konvoy.mesosphere.io/v1beta2
metadata:
  name: kbsys-k8s
  creationTimestamp: "2020-09-21T03:59:13Z"
spec:
  imageRegistries:
    - server: https://www.kb-sys.co.kr
      username: "admin"
      password: "admin1234"
      default: true
  kubernetes:
    version: 1.17.11
    controlPlane:
      controlPlaneEndpointOverride: "192.168.0.230:6443"
      certificate: {}
      keepalived: {}
    networking:
      podSubnet: 192.168.100.0/24
      serviceSubnet: 10.0.0.0/18
      iptables:
        addDefaultRules: false
    cloudProvider:
      provider: none
    admissionPlugins:
      enabled:
        - AlwaysPullImages
        - NodeRestriction
  containerNetworking:
    calico:
      version: v3.13.5
      encapsulation: ipip
      mtu: 1480
  containerRuntime:
    containerd:
      version: 1.3.7
  osPackages:
    enableAdditionalRepositories: false
  nodePools:
    - name: worker
  addons:
    - configRepository: /opt/konvoy/artifacts/kubeaddons-dispatch
      configVersion: stable-1.17-1.2.2
      addonsList:
        - name: dispatch
          enabled: false
    - configRepository: /opt/konvoy/artifacts/kubeaddons-kommander
      configVersion: stable-1.17-1.1.2
      addonsList:
        - name: kommander
          enabled: false
    - configRepository: /opt/konvoy/artifacts/kubernetes-base-addons
      configVersion: stable-1.17-2.2.0
      addonsList:
        - name: cert-manager
          enabled: true
        - name: dashboard
          enabled: true
        - name: defaultstorageclass-protection
          enabled: true
        - name: dex
          enabled: true
        - name: dex-k8s-authenticator
          enabled: true
        - name: elasticsearch
          enabled: false
        - name: elasticsearch-curator
          enabled: false
        - name: elasticsearchexporter
          enabled: false
        - name: external-dns
          enabled: false
        - name: flagger
          enabled: false
        - name: fluentbit
          enabled: true
        - name: gatekeeper
          enabled: true
        - name: istio # Istio is currently in Preview
          enabled: false
        - name: kibana
          enabled: false
        - name: konvoyconfig
          enabled: true
        - name: kube-oidc-proxy
          enabled: true
        - name: localvolumeprovisioner
          enabled: true
        - name: metallb
          enabled: true
          values: |
            configInline:
              address-pools:
              - name: default
                protocol: layer2
                # configure addresses for your network
                addresses: [192.168.0.231-192.168.0.233]
        - name: nvidia
          enabled: false
        - name: opsportal
          enabled: true
        - name: prometheus
          enabled: false
        - name: prometheusadapter
          enabled: false
        - name: reloader
          enabled: true
        - name: traefik
          enabled: true
        - name: traefik-forward-auth
          enabled: true
        - name: velero
          enabled: true
  version: v1.5.2

